/*
 * Build-time flag generator for LYKNCTF 2026 KeygenMe.  NOT shipped.
 *
 *   usage: gen_flag [pass1.exe]
 *
 * Pass 1 (no arg): emit flag_enc.h with a ZERO .text hash so the crackme
 *   can be compiled to measure its real .text.
 * Pass 2 (with arg): read pass1.exe, hash its .text exactly as the runtime
 *   self-hash does, and emit the real flag_enc.h.
 *
 * Emits: g_ct[96] (ciphertext), g_tag[8], g_encu[] (obfuscated target user).
 * Shares keygen_core.h / flagcrypt.h / sha256.h with the crackme.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <windows.h>

#include "keygen_core.h"
#include "flagcrypt.h"
#include "secret_config.h"

/* Hash Misc.VirtualSize bytes of the on-disk .text at PointerToRawData,
 * matching selfhash.h's in-memory hash (ASLR is disabled at link time). */
static int text_hash_of_file(const char *path, unsigned char out[32])
{
    FILE *f = fopen(path, "rb");
    long sz;
    unsigned char *buf;
    IMAGE_DOS_HEADER *dos;
    IMAGE_NT_HEADERS *nt;
    IMAGE_SECTION_HEADER *sec;
    int i, ok = 0;

    if (!f) return 0;
    fseek(f, 0, SEEK_END); sz = ftell(f); fseek(f, 0, SEEK_SET);
    buf = (unsigned char *)malloc((size_t)sz);
    if (!buf) { fclose(f); return 0; }
    if (fread(buf, 1, (size_t)sz, f) != (size_t)sz) { free(buf); fclose(f); return 0; }
    fclose(f);

    dos = (IMAGE_DOS_HEADER *)buf;
    nt  = (IMAGE_NT_HEADERS *)(buf + dos->e_lfanew);
    sec = IMAGE_FIRST_SECTION(nt);
    for (i = 0; i < nt->FileHeader.NumberOfSections; i++) {
        const unsigned char *nm = sec[i].Name;
        if (nm[0]=='.' && nm[1]=='t' && nm[2]=='e' && nm[3]=='x' && nm[4]=='t') {
            sha256(buf + sec[i].PointerToRawData, sec[i].Misc.VirtualSize, out);
            ok = 1;
            break;
        }
    }
    free(buf);
    return ok;
}

static void emit_bytes(FILE *f, const char *name, const unsigned char *b, int n)
{
    int i;
    fprintf(f, "static const unsigned char %s[%d] = {\n    ", name, n);
    for (i = 0; i < n; i++) {
        fprintf(f, "0x%02X,", b[i]);
        if ((i + 1) % 12 == 0) fprintf(f, "\n    ");
        else fprintf(f, " ");
    }
    fprintf(f, "\n};\n");
}

int main(int argc, char **argv)
{
    unsigned char text_hash[32];
    const char *U = TARGET_USER;
    const char *flag = FLAG_TEXT;
    int ulen = (int)strlen(U);
    int flen = (int)strlen(flag);
    char serial[32];
    unsigned char K0[32], ks[FLAG_CTLEN], pt[FLAG_CTLEN], ct[FLAG_CTLEN];
    unsigned char tag[8], encu[128];
    int i;
    FILE *f;

    memset(text_hash, 0, 32);
    if (argc >= 2) {
        if (!text_hash_of_file(argv[1], text_hash)) {
            fprintf(stderr, "[gen_flag] cannot read .text of %s\n", argv[1]);
            return 1;
        }
    }
    if (flen >= FLAG_CTLEN) { fprintf(stderr, "[gen_flag] flag too long\n"); return 1; }
    if (ulen > 120)        { fprintf(stderr, "[gen_flag] user too long\n"); return 1; }

    /* serial for the hidden user (clean run: dbg = 0) */
    lykn_keygen(U, ulen, 0, serial);

    /* K0 = SHA256(U || 0x1F || serial || 0x1F || text_hash || 0) */
    lykn_derive_key((const unsigned char *)U, ulen,
                    (const unsigned char *)serial, (int)strlen(serial),
                    text_hash, 0, K0);

    /* encrypt padded flag */
    memset(pt, 0, FLAG_CTLEN);
    memcpy(pt, flag, (size_t)flen);
    lykn_keystream(K0, ks);
    for (i = 0; i < FLAG_CTLEN; i++) ct[i] = pt[i] ^ ks[i];

    lykn_tag((const unsigned char *)flag, flen, tag);
    lykn_obf_user((const unsigned char *)U, ulen, encu);

    f = fopen("flag_enc.h", "w");
    if (!f) { fprintf(stderr, "[gen_flag] cannot write flag_enc.h\n"); return 1; }
    fprintf(f, "/* Auto-generated by gen_flag. DO NOT hand-edit. */\n");
    fprintf(f, "#ifndef FLAG_ENC_H\n#define FLAG_ENC_H\n\n");
    fprintf(f, "#define G_ENCU_LEN %d\n\n", ulen);
    emit_bytes(f, "g_ct",   ct,   FLAG_CTLEN);
    fprintf(f, "\n");
    emit_bytes(f, "g_tag",  tag,  8);
    fprintf(f, "\n");
    emit_bytes(f, "g_encu", encu, ulen);
    fprintf(f, "\n#endif /* FLAG_ENC_H */\n");
    fclose(f);

    fprintf(stderr, "[gen_flag] %s  U=%d flag=%d  text_hash[0..3]=%02X%02X%02X%02X\n",
            (argc >= 2 ? "REAL" : "DUMMY(zero-hash)"),
            ulen, flen, text_hash[0], text_hash[1], text_hash[2], text_hash[3]);
    return 0;
}
