#!/usr/bin/env python3
"""
Build tool for chall8. Computes the per-byte 16-bit checkpoints CHK[i] by
running the MIX chain forward on the real flag, and emits src/check_data.h.

Single source of truth for MIX (mirrors src/mix.h). Later stages add the VM
bytecode + rolling encryption here; for now it just emits CHK + IV.

    usage: python gen.py [pass1.exe]      (exe arg -> runtime IV from .text hash)
"""
import os
import re
import sys
import struct
import hashlib

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "src")
MASK = 0xFFFFFFFF


def rotl(x, r): x &= MASK; return ((x << r) | (x >> (32 - r))) & MASK


def MIX(s, c, rc):
    s ^= (c * 0x53 + rc) & MASK; s &= MASK
    s = rotl(s, 7)
    s ^= s >> 13
    s = ((s + rc) & MASK) * 0x9C5AB3D7 & MASK
    s = rotl(s, 11)
    s ^= s >> 17
    s = (s + 0x3F1E5C2B) & MASK
    return s


def chain(inner, iv):
    state = iv
    rc = iv ^ 0xA5A5A5A5
    chk = []
    for c in inner:
        state = MIX(state, c, rc)
        chk.append(state & 0xFFFF)
        rc = rotl((rc * 0x9C5AB3D7 + 0x3F1E5C2B) & MASK, 13)
    return chk


# ---- VM: assemble MIX into bytecode, then chain-encrypt it ---------------
OPS = {
    "LDS": 0x10, "LDC": 0x11, "LDR": 0x12, "IMM": 0x13, "MOV": 0x14,
    "ADD": 0x15, "SUB": 0x16, "XOR": 0x17, "MUL": 0x18, "MULI": 0x19,
    "ADDI": 0x1A, "XORI": 0x1B, "ROL": 0x1C, "ROR": 0x1D, "SHRX": 0x1E,
    "OUT": 0x1F, "HALT": 0x20,
}
VM_SEED = 0xC0DE1234


def asm_mix():
    """Straight-line MIX program (mirrors src/mix.h MIX())."""
    prog = [
        ("LDS", 0), ("LDC", 1), ("LDR", 2),        # R0=state R1=c R2=rc
        ("MOV", 3, 1), ("MULI", 3, 0x53), ("ADD", 3, 2),   # R3 = c*0x53 + rc
        ("XOR", 0, 3),                              # s ^= R3
        ("ROL", 0, 7),
        ("SHRX", 0, 13),                            # s ^= s>>13
        ("ADD", 0, 2),                              # s += rc
        ("MULI", 0, 0x9C5AB3D7),
        ("ROL", 0, 11),
        ("SHRX", 0, 17),
        ("ADDI", 0, 0x3F1E5C2B),
        ("OUT", 0), ("HALT",),
    ]
    out = bytearray()
    for ins in prog:
        op = ins[0]; out.append(OPS[op])
        if op in ("LDS", "LDC", "LDR", "OUT"):
            out.append(ins[1])
        elif op in ("MOV", "ADD", "SUB", "XOR", "MUL"):
            out += bytes([ins[1], ins[2]])
        elif op in ("IMM", "MULI", "ADDI", "XORI"):
            out.append(ins[1]); out += struct.pack("<I", ins[2] & MASK)
        elif op in ("ROL", "ROR", "SHRX"):
            out += bytes([ins[1], ins[2]])
        elif op == "HALT":
            pass
        else:
            raise ValueError(op)
    return bytes(out)


def chain_encrypt(plain, seed):
    """Self-synchronizing stream cipher keyed on PLAINTEXT history: decrypting
    byte j needs the state produced by plain[0..j-1], so the program cannot be
    laid out statically without emulating the chain."""
    ks = seed & MASK
    enc = bytearray()
    for p in plain:
        mask = (ks >> 24) & 0xFF
        enc.append(p ^ mask)
        ks = (rotl(ks ^ p, 11) * 0x9C5AB3D7 + 0x3F1E5C2B) & MASK
    return bytes(enc)


def read_flag():
    txt = open(os.path.join(SRC, "secret_config.h")).read()
    flag = re.search(r'FLAG_TEXT\s+"([^"]*)"', txt).group(1)
    inner = flag[flag.index("{") + 1:flag.index("}")]
    n = int(re.search(r'FLAG_INNER_LEN\s+(\d+)', txt).group(1))
    assert len(inner) == n, f"inner {len(inner)} != {n}"
    return flag, inner.encode("latin1")


def text_hash_of(path):
    data = open(path, "rb").read()
    e = struct.unpack_from("<I", data, 0x3C)[0]
    nsec = struct.unpack_from("<H", data, e + 6)[0]
    optsz = struct.unpack_from("<H", data, e + 20)[0]
    tbl = e + 24 + optsz
    for i in range(nsec):
        o = tbl + i * 40
        if data[o:o + 8].rstrip(b"\x00") == b".text":
            vs, va, rs, rp = struct.unpack_from("<IIII", data, o + 8)
            return hashlib.sha256(data[rp:rp + vs]).digest()
    raise RuntimeError(".text not found")


# Runtime IV = u32le(SHA256(.text)[0:4]) XOR TLS_SEED (set pre-main).
TLS_SEED = 0xB16B00B5


def main():
    flag, inner = read_flag()
    iv = TLS_SEED                                     # dummy pass (text_hash = 0)
    if len(sys.argv) >= 2:
        th = text_hash_of(sys.argv[1])
        iv = (struct.unpack_from("<I", th, 0)[0] ^ TLS_SEED) & MASK
    chk = chain(list(inner), iv)

    prog = asm_mix()
    code_enc = chain_encrypt(prog, VM_SEED)

    with open(os.path.join(SRC, "check_data.h"), "w") as f:
        f.write("/* Auto-generated by tools/gen.py. DO NOT hand-edit. */\n")
        f.write("#ifndef CHECK_DATA_H\n#define CHECK_DATA_H\n\n")
        f.write("#define CHECK_N   %d\n" % len(inner))
        f.write("#define CODE_LEN  %d\n" % len(code_enc))
        f.write("#define VM_SEED   0x%08Xu\n\n" % VM_SEED)
        f.write("static const unsigned short g_chk[CHECK_N] = {\n    ")
        for i, v in enumerate(chk):
            f.write("0x%04X," % v)
            f.write("\n    " if (i + 1) % 8 == 0 else " ")
        f.write("\n};\n\n")
        f.write("static const unsigned char g_code_enc[CODE_LEN] = {\n    ")
        for i, b in enumerate(code_enc):
            f.write("0x%02X," % b)
            f.write("\n    " if (i + 1) % 12 == 0 else " ")
        f.write("\n};\n\n")
        f.write("#ifdef CHECK_HARNESS\n")
        f.write("#define CHECK_IV  0x%08Xu\n" % iv)
        f.write('static const unsigned char g_inner[CHECK_N] = { ')
        f.write(", ".join("0x%02X" % b for b in inner))
        f.write(" };\n#endif\n\n")
        f.write("#endif /* CHECK_DATA_H */\n")

    print(f"[gen] inner='{inner.decode()}' N={len(inner)} IV=0x{iv:08X}")
    print(f"[gen] MIX bytecode = {len(prog)} bytes, chain-encrypted")
    print(f"[gen] CHK = {' '.join('%04X' % v for v in chk)}")


if __name__ == "__main__":
    main()
